/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 bedroom.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const BedroomModel = (props) => {
  const { nodes, materials } = useGLTF('/models/bedroom.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-8.545, 0.397, -1.008]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[0.012, 0.135, 0.222]}>
        <mesh geometry={nodes.Object_151.geometry} material={materials['Material.103']} />
        <mesh geometry={nodes.Object_152.geometry} material={materials['Material.001']} />
      </group>
      <group position={[-8.545, 0.651, -0.685]} rotation={[-1.222, 0, -Math.PI / 2]} scale={[0.012, 0.23, 0.222]}>
        <mesh geometry={nodes.Object_164.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_165.geometry} material={materials['Material.103']} />
      </group>
      <group position={[-8.975, 0.78, -1.608]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_327.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_328.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.911, 0.78, -1.648]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_333.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_334.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.786, 0.78, -1.648]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_336.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_337.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.827, 0.78, -1.648]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_339.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_340.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.868, 0.78, -1.648]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_342.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_343.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.673, 0.78, -1.648]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_345.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_346.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.633, 0.78, -1.648]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_348.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_349.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.591, 0.78, -1.648]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_351.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_352.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.716, 0.78, -1.648]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_354.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_355.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.422, 0.78, -1.648]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_357.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_358.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.463, 0.78, -1.648]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_360.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_361.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.504, 0.78, -1.648]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_363.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_364.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.886, 0.78, -1.608]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_306.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_307.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.364, 0.78, -1.648]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_381.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_382.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.322, 0.78, -1.648]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_384.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_385.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.846, 0.78, -1.608]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_309.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_310.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.718, 0.78, -1.608]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_312.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_313.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.975, 0.78, -1.648]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_330.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_331.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.677, 0.78, -1.608]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_315.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_316.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.762, 0.78, -1.608]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_318.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_319.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.804, 0.78, -1.608]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_321.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_322.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.93, 0.78, -1.608]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_324.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_325.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.504, 0.78, -1.607]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_366.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_367.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.463, 0.78, -1.607]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_369.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_370.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.422, 0.78, -1.607]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_372.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_373.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.322, 0.78, -1.607]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_375.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_376.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.61, 0.78, -1.608]} rotation={[Math.PI, 0, Math.PI]} scale={[0.034, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_408.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_409.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.135, 0.774, -1.575]} rotation={[-Math.PI, Math.PI / 3, -Math.PI]} scale={[0.04, 0.01, 0.028]}>
        <mesh geometry={nodes.Object_245.geometry} material={materials['Material.092']} />
        <mesh geometry={nodes.Object_246.geometry} material={materials['Material.024']} />
      </group>
      <group position={[-8.364, 0.78, -1.607]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_378.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_379.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.364, 0.78, -1.526]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_387.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_388.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.322, 0.78, -1.526]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_390.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_391.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.322, 0.78, -1.567]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_393.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_394.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.364, 0.78, -1.567]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_396.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_397.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.364, 0.78, -1.496]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_399.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_400.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.422, 0.78, -1.497]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_417.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_418.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.463, 0.78, -1.497]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_420.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_421.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.504, 0.78, -1.497]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_423.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_424.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.463, 0.78, -1.534]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_426.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_427.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.318, 0.78, -1.496]} rotation={[Math.PI, 0, Math.PI]} scale={[0.011, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_402.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_403.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.631, 0.78, -1.57]} rotation={[Math.PI, 0, Math.PI]} scale={[0.011, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_405.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_406.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.61, 0.78, -1.533]} rotation={[Math.PI, 0, Math.PI]} scale={[0.034, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_411.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_412.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.591, 0.78, -1.57]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_414.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_415.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.972, 0.78, -1.499]} rotation={[Math.PI, 0, Math.PI]} scale={[0.018, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_429.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_430.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.975, 0.78, -1.533]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_432.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_433.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.96, 0.78, -1.57]} rotation={[Math.PI, 0, Math.PI]} scale={[0.03, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_435.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_436.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.804, 0.78, -1.57]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_273.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_274.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.762, 0.78, -1.57]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_276.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_277.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.677, 0.78, -1.57]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_279.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_280.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.718, 0.78, -1.57]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_282.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_283.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.757, 0.78, -1.499]} rotation={[Math.PI, 0, Math.PI]} scale={[0.05, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_438.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_439.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.886, 0.78, -1.499]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_252.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_253.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.846, 0.78, -1.57]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_264.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_265.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.886, 0.78, -1.533]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_255.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_256.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.718, 0.78, -1.533]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_285.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_286.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.677, 0.78, -1.533]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_288.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_289.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.762, 0.78, -1.533]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_291.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_292.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.804, 0.78, -1.533]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_294.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_295.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.926, 0.78, -1.533]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_258.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_259.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.886, 0.78, -1.57]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_261.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_262.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.846, 0.78, -1.533]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_267.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_268.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.837, 0.78, -1.499]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_270.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_271.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.926, 0.78, -1.499]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_242.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_243.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.676, 0.78, -1.499]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_297.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_298.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.591, 0.78, -1.499]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_300.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_301.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.632, 0.78, -1.499]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh geometry={nodes.Object_303.geometry} material={materials['keyboard_light.052']} />
        <mesh geometry={nodes.Object_304.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-8.154, 0.776, -1.61]} rotation={[1.343, 0.13, -2.08]} scale={[0.015, 0.002, 0.011]}>
        <mesh geometry={nodes.Object_248.geometry} material={materials.material_0} position={[0, -0.001, 0]} />
      </group>
      <group position={[-8.559, 1.07, -1.91]} rotation={[-Math.PI / 2, -1.571, 0]} scale={[0.14, 0.814, 0.351]}>
        <mesh geometry={nodes.Object_102.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_103.geometry} material={materials['Material.104']} />
      </group>
      <group position={[-8.559, 0.755, -1.578]} rotation={[0, -1.571, 0]} scale={[0.166, 0.389, 0.574]}>
        <mesh geometry={nodes.Object_132.geometry} material={materials['Material.027']} />
        <mesh geometry={nodes.Object_133.geometry} material={materials['Matériau.030']} />
      </group>
      <group position={[-9.162, 1.07, -1.661]} rotation={[0, -Math.PI / 4, Math.PI / 2]} scale={[0.14, 0.814, 0.351]}>
        <mesh geometry={nodes.Object_135.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_136.geometry} material={materials['Material.104']} />
      </group>
      <group position={[-7.956, 1.07, -1.658]} rotation={[-Math.PI, -Math.PI / 4, -Math.PI / 2]} scale={[0.14, 0.814, 0.351]}>
        <mesh geometry={nodes.Object_140.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_141.geometry} material={materials['Material.104']} />
      </group>
      <group position={[-8.651, 0.769, -1.578]} rotation={[0, -1.571, 0]} scale={[0.105, 0.248, 0.365]}>
        <mesh geometry={nodes.Object_239.geometry} material={materials['Material.092']} />
        <mesh geometry={nodes.Object_240.geometry} material={materials['Material.027']} />
      </group>
      <group position={[-9.951, 1.486, 0.001]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[1.09, 0.559, 0.746]}>
        <mesh geometry={nodes.Object_481.geometry} material={materials['Material.099']} position={[0, 0, 0.027]} />
      </group>
      <group position={[-8.559, 0.727, -1.699]} rotation={[0, -1.571, 0]} scale={[0.382, 1.144, 1.33]}>
        <mesh geometry={nodes.Object_95.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Object_96.geometry} material={materials['keyboard_light.052']} />
      </group>
      <group position={[-9.802, 2.298, -0.603]} rotation={[0, -1.571, 0]}>
        <group position={[0, -0.08, 0]}>
          <mesh geometry={nodes.Object_8.geometry} material={materials['Material.092']} />
          <mesh geometry={nodes.Object_10.geometry} material={materials['Material.001']} position={[0, 0, -0.021]} />
          <mesh geometry={nodes.Object_12.geometry} material={materials['Material.001']} position={[0.352, 0, -0.021]} />
          <mesh geometry={nodes.Object_14.geometry} material={materials['Material.001']} position={[-0.352, 0, -0.021]} />
          <mesh geometry={nodes.Object_16.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Object_18.geometry} material={materials['Material.001']} position={[0, 0, 0.021]} />
          <mesh geometry={nodes.Object_20.geometry} material={materials['Material.001']} position={[0.352, 0, 0.021]} />
          <mesh geometry={nodes.Object_22.geometry} material={materials['Material.001']} position={[-0.352, 0, 0.021]} />
          <mesh geometry={nodes.Object_24.geometry} material={materials['Material.001']} position={[0.352, 0, 0]} />
          <mesh geometry={nodes.Object_26.geometry} material={materials['Material.001']} position={[-0.352, 0, 0]} />
          <mesh geometry={nodes.Object_28.geometry} material={materials['Material.003']} position={[0, -1.59, 0]} />
        </group>
        <mesh geometry={nodes.Object_6.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.material_0} position={[-0.47, -0.03, 0.023]} />
        <mesh geometry={nodes.Object_32.geometry} material={materials['Material.001']} position={[0.47, -0.03, 0.023]} />
      </group>
      <group position={[-9.803, 2.298, 0.608]} rotation={[0, -1.571, 0]}>
        <group position={[0, -0.08, 0]}>
          <mesh geometry={nodes.Object_36.geometry} material={materials['Material.092']} />
          <mesh geometry={nodes.Object_38.geometry} material={materials['Material.001']} position={[0, 0, -0.021]} />
          <mesh geometry={nodes.Object_40.geometry} material={materials['Material.001']} position={[0.352, 0, -0.021]} />
          <mesh geometry={nodes.Object_42.geometry} material={materials['Material.001']} position={[-0.352, 0, -0.021]} />
          <mesh geometry={nodes.Object_44.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Object_46.geometry} material={materials['Material.001']} position={[0, 0, 0.021]} />
          <mesh geometry={nodes.Object_48.geometry} material={materials['Material.001']} position={[0.352, 0, 0.021]} />
          <mesh geometry={nodes.Object_50.geometry} material={materials['Material.001']} position={[-0.352, 0, 0.021]} />
          <mesh geometry={nodes.Object_52.geometry} material={materials['Material.001']} position={[0.352, 0, 0]} />
          <mesh geometry={nodes.Object_54.geometry} material={materials['Material.001']} position={[-0.352, 0, 0]} />
          <mesh geometry={nodes.Object_56.geometry} material={materials['Material.003']} position={[0, -1.59, 0]} />
        </group>
        <mesh geometry={nodes.Object_34.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Object_58.geometry} material={materials.material_0} position={[-0.47, -0.03, 0.023]} />
        <mesh geometry={nodes.Object_60.geometry} material={materials['Material.001']} position={[0.47, -0.03, 0.023]} />
      </group>
      <mesh geometry={nodes.Object_79.geometry} material={materials['Matériau.020']} position={[-9.364, 0.18, -1.705]} rotation={[Math.PI, 0, Math.PI]} scale={[0.234, 0.153, 0.291]} />
      <mesh geometry={nodes.Object_69.geometry} material={materials['Material.099']} position={[-9.916, 1.481, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[2.151, 0.031, 1.454]} />
      <mesh geometry={nodes.Object_83.geometry} material={materials['Matériau.018']} position={[-7.75, 0.525, -1.705]} rotation={[Math.PI, 0, Math.PI]} scale={[0.234, 0.153, 0.291]} />
      <mesh geometry={nodes.Object_81.geometry} material={materials['Matériau.019']} position={[-9.364, 0.525, -1.705]} rotation={[Math.PI, 0, Math.PI]} scale={[0.234, 0.153, 0.291]} />
      <mesh geometry={nodes.Object_85.geometry} material={materials['Matériau.017']} position={[-7.75, 0.18, -1.705]} rotation={[Math.PI, 0, Math.PI]} scale={[0.234, 0.153, 0.291]} />
      <mesh geometry={nodes.Object_87.geometry} material={materials.lever} position={[-9.364, 0.298, -1.458]} rotation={[Math.PI, 0, Math.PI]} scale={[0.098, 0.006, 0.064]} />
      <mesh geometry={nodes.Object_89.geometry} material={materials.lever} position={[-9.364, 0.638, -1.458]} rotation={[Math.PI, 0, Math.PI]} scale={[0.098, 0.006, 0.064]} />
      <mesh geometry={nodes.Object_91.geometry} material={materials.lever} position={[-7.75, 0.638, -1.458]} rotation={[Math.PI, 0, Math.PI]} scale={[0.098, 0.006, 0.064]} />
      <mesh geometry={nodes.Object_93.geometry} material={materials.lever} position={[-7.75, 0.298, -1.458]} rotation={[Math.PI, 0, Math.PI]} scale={[0.098, 0.006, 0.064]} />
      <mesh geometry={nodes.Object_98.geometry} material={materials.material_0} position={[-9.364, 0.7, -1.705]} rotation={[Math.PI, 0, Math.PI]} scale={[0.205, 0.025, 0.255]} />
      <mesh geometry={nodes.Object_100.geometry} material={materials.material_0} position={[-7.748, 0.7, -1.705]} rotation={[Math.PI, 0, Math.PI]} scale={[0.205, 0.025, 0.255]} />
      <mesh geometry={nodes.Object_130.geometry} material={materials.screen} position={[-8.562, 0.759, -1.977]} scale={[0.033, 0.004, 0.033]} />
      <mesh geometry={nodes.Object_138.geometry} material={materials.screen} position={[-9.212, 0.759, -1.707]} rotation={[0, Math.PI / 4, 0]} scale={[0.033, 0.004, 0.033]} />
      <mesh geometry={nodes.Object_143.geometry} material={materials.screen} position={[-7.91, 0.759, -1.707]} rotation={[0, -Math.PI / 4, 0]} scale={[0.033, 0.004, 0.033]} />
      <mesh geometry={nodes.Object_149.geometry} material={materials.lever} position={[-8.545, 0.365, -1.008]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.021, 0.061, 0.061]} />
      <mesh geometry={nodes.Object_171.geometry} material={materials['Matériau.007']} position={[-7.456, 1.03, -1.684]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.252, 0.164, 0.313]} />
      <mesh geometry={nodes.Object_173.geometry} material={materials.lever} position={[-7.565, 1.344, -1.415]} rotation={[Math.PI, 0, Math.PI]} scale={[0.024, 0.004, 0.016]} />
      <mesh geometry={nodes.Object_175.geometry} material={materials.lever} position={[-7.485, 1.344, -1.415]} rotation={[Math.PI, 0, Math.PI]} scale={[0.016, 0.002, 0.01]} />
      <mesh geometry={nodes.Object_177.geometry} material={materials.lever} position={[-7.417, 1.344, -1.415]} rotation={[Math.PI, 0, Math.PI]} scale={[0.016, 0.002, 0.01]} />
      <mesh geometry={nodes.Object_213.geometry} material={materials['keyboard_light.052']} position={[-7.583, 0.961, -1.781]} rotation={[-2.269, 0, -Math.PI / 2]} scale={[0.094, 0.003, 0.016]} />
      <mesh geometry={nodes.Object_215.geometry} material={materials['keyboard_light.052']} position={[-7.583, 1.082, -1.781]} rotation={[-2.269, 0, -Math.PI / 2]} scale={[0.065, 0.002, 0.011]} />
      <mesh geometry={nodes.Object_217.geometry} material={materials['keyboard_light.052']} position={[-7.583, 0.893, -1.716]} rotation={[-2.269, 0, -Math.PI / 2]} scale={[0.094, 0.003, 0.016]} />
      <mesh geometry={nodes.Object_219.geometry} material={materials['keyboard_light.052']} position={[-7.583, 0.877, -1.599]} rotation={[-2.269, 0, -Math.PI / 2]} scale={[0.069, 0.002, 0.012]} />
      <mesh geometry={nodes.Object_223.geometry} material={materials['Material.025']} position={[-7.342, 1.342, -1.412]} rotation={[Math.PI, 0, Math.PI]} scale={[0.001, 0.001, 0.01]} />
      <mesh geometry={nodes.Object_147.geometry} material={materials['Material.103']} position={[-8.55, 0.104, -1.011]} scale={[0.045, 0.025, 0.045]} />
      <mesh geometry={nodes.Object_154.geometry} material={materials.lever} position={[-8.309, 0.052, -0.935]} rotation={[-Math.PI / 2, 0, -1.92]} scale={[0.027, 0.012, 0.027]} />
      <mesh geometry={nodes.Object_156.geometry} material={materials.lever} position={[-8.4, 0.052, -1.215]} rotation={[-Math.PI / 2, 0, -0.611]} scale={[0.027, 0.012, 0.027]} />
      <mesh geometry={nodes.Object_145.geometry} material={materials['Material.001']} position={[-8.549, 0.178, -1.01]} rotation={[3.135, -0.046, 0.023]} scale={[0.024, 0.012, 0.024]} />
      <mesh geometry={nodes.Object_158.geometry} material={materials.lever} position={[-8.699, 0.052, -1.216]} rotation={[-Math.PI / 2, 0, 0.611]} scale={[0.027, 0.012, 0.027]} />
      <mesh geometry={nodes.Object_160.geometry} material={materials.lever} position={[-8.793, 0.052, -0.932]} rotation={[-Math.PI / 2, 0, 1.92]} scale={[0.027, 0.012, 0.027]} />
      <mesh geometry={nodes.Object_162.geometry} material={materials.lever} position={[-8.55, 0.052, -0.754]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[0.027, 0.012, 0.027]} />
      <mesh geometry={nodes.Object_179.geometry} material={materials.material_0} position={[-7.34, 1.323, -1.428]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.013, -0.004, -0.013]} />
      <mesh geometry={nodes.Object_225.geometry} material={materials['Matériau.026']} position={[-7.455, 1.198, -1.443]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-0.072, -0.005, -0.072]} />
      <mesh geometry={nodes.Object_209.geometry} material={materials['Matériau.027']} position={[-7.455, 1.031, -1.443]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-0.072, -0.005, -0.072]} />
      <mesh geometry={nodes.Object_211.geometry} material={materials['Matériau.029']} position={[-7.455, 0.865, -1.443]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-0.072, -0.005, -0.072]} />
      <mesh geometry={nodes.Object_221.geometry} material={materials['Material.024']} position={[-7.455, 1.195, -1.878]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-0.072, -0.005, -0.072]} />
      <mesh geometry={nodes.Object_250.geometry} material={materials['Material.099']} position={[-7.292, 1.03, -1.685]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[0.203, 0.203, 0.251]} />
      <mesh geometry={nodes.Object_493.geometry} material={materials['keyboard_light.052']} position={[-7.582, 1.178, -1.52]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.09} />
      <group position={[-9.139, 0, 1.219]} rotation={[-Math.PI / 2, 0, 1.214]} scale={0.302}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[-9.114, -0.846, 84.666]} rotation={[-Math.PI / 2, 0, 0.495]} scale={100}>
            <mesh geometry={nodes.Guitar_Stand_Guitar_Stand_0.geometry} material={materials.Guitar_Stand} position={[1.07, 1.698, 0.049]} />
          </group>
          <group position={[-12.809, 258.612, 80.447]} rotation={[-1.875, -0.174, 0.504]} scale={100}>
            <mesh geometry={nodes.Guitar_Telecaster_Guitar_telecaster_0.geometry} material={materials.Guitar_telecaster} position={[1.13, 1.542, 0.613]} />
          </group>
          <group position={[-230.406, 0, -90]} rotation={[-Math.PI / 2, 0, Math.PI / 6]} scale={110}>
            <mesh geometry={nodes.Vox_Amp_vox_amp_0.geometry} material={materials.vox_amp} position={[0, 0, 0.045]} />
          </group>
          <group position={[267.623, 0, -70.873]} rotation={[-Math.PI / 2, 0, 0.175]} scale={110}>
            <mesh geometry={nodes.Vox_Amp001_vox_amp_0.geometry} material={materials.vox_amp} position={[0.312, 1.284, 0.045]} rotation={[0, 0, -0.308]} />
          </group>
        </group>
      </group>
      <mesh geometry={nodes.Cube.geometry} material={materials['Matériau.032']} position={[-9.948, 1.153, -1.626]} rotation={[-1.56, -0.004, Math.PI / 2]} scale={[25.581, 1.019, 2.144]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Matériau.034']} position={[-9.954, 1.126, 1.659]} rotation={[0, -0.004, Math.PI / 2]} scale={[54.97, 1.326, 1.01]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Matériau.033']} position={[-9.951, 0.395, 0.01]} rotation={[0, -0.004, Math.PI / 2]} scale={[18.743, 1.019, 2.179]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Matériau.006']} position={[-7.803, 1.156, -2.105]} rotation={[2.965, -1.552, -1.748]} scale={[54.116, 1.019, 4.075]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.004']} position={[-7.812, -0.091, 0.044]} rotation={[-3.131, 0, 3.137]} />
    </group>
  )
}

useGLTF.preload('/models/bedroom.glb')

export default BedroomModel;
