/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 bedroom.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function BedroomModel(props) {
  const { nodes, materials } = useGLTF('/models/bedroom.glb')
  return (
    <group {...props} dispose={null}>
        <pointLight position={[2, 2.5, 0]} intensity={800} color={"white"} castShadow/>
        <group position={[-0.657, 0.397, -1.008]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[0.012, 0.135, 0.222]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_151.geometry} material={materials['Material.103']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_152.geometry} material={materials['Material.001']} />
      </group>
      <group position={[-0.657, 0.651, -0.685]} rotation={[-1.222, 0, -Math.PI / 2]} scale={[0.012, 0.23, 0.222]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_164.geometry} material={materials['Material.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_165.geometry} material={materials['Material.103']} />
      </group>
      <group position={[-1.086, 0.78, -1.608]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_327.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_328.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-1.023, 0.78, -1.648]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_333.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_334.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.898, 0.78, -1.648]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_336.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_337.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.939, 0.78, -1.648]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_339.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_340.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.98, 0.78, -1.648]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_342.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_343.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.785, 0.78, -1.648]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_345.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_346.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.744, 0.78, -1.648]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_348.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_349.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.703, 0.78, -1.648]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_351.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_352.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.828, 0.78, -1.648]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_354.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_355.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.533, 0.78, -1.648]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_357.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_358.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.575, 0.78, -1.648]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_360.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_361.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.615, 0.78, -1.648]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_363.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_364.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.998, 0.78, -1.608]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_306.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_307.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.475, 0.78, -1.648]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_381.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_382.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.434, 0.78, -1.648]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_384.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_385.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.957, 0.78, -1.608]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_309.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_310.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.829, 0.78, -1.608]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_312.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_313.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-1.086, 0.78, -1.648]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_330.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_331.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.789, 0.78, -1.608]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_315.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_316.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.873, 0.78, -1.608]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_318.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_319.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.916, 0.78, -1.608]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_321.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_322.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-1.041, 0.78, -1.608]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_324.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_325.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.615, 0.78, -1.607]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_366.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_367.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.575, 0.78, -1.607]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_369.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_370.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.533, 0.78, -1.607]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_372.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_373.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.434, 0.78, -1.607]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_375.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_376.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.721, 0.78, -1.608]} rotation={[Math.PI, 0, Math.PI]} scale={[0.034, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_408.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_409.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.246, 0.774, -1.575]} rotation={[-Math.PI, Math.PI / 3, -Math.PI]} scale={[0.04, 0.01, 0.028]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_245.geometry} material={materials['Material.092']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_246.geometry} material={materials['Material.024']} />
      </group>
      <group position={[-0.475, 0.78, -1.607]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_378.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_379.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.475, 0.78, -1.526]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_387.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_388.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.434, 0.78, -1.526]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_390.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_391.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.434, 0.78, -1.567]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_393.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_394.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.475, 0.78, -1.567]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_396.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_397.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.475, 0.78, -1.496]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_399.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_400.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.533, 0.78, -1.497]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_417.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_418.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.575, 0.78, -1.497]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_420.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_421.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.615, 0.78, -1.497]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_423.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_424.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.575, 0.78, -1.534]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_426.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_427.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.43, 0.78, -1.496]} rotation={[Math.PI, 0, Math.PI]} scale={[0.011, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_402.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_403.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.742, 0.78, -1.57]} rotation={[Math.PI, 0, Math.PI]} scale={[0.011, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_405.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_406.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.721, 0.78, -1.533]} rotation={[Math.PI, 0, Math.PI]} scale={[0.034, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_411.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_412.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.703, 0.78, -1.57]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_414.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_415.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-1.084, 0.78, -1.499]} rotation={[Math.PI, 0, Math.PI]} scale={[0.018, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_429.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_430.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-1.086, 0.78, -1.533]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_432.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_433.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-1.072, 0.78, -1.57]} rotation={[Math.PI, 0, Math.PI]} scale={[0.03, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_435.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_436.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.916, 0.78, -1.57]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_273.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_274.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.873, 0.78, -1.57]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_276.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_277.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.789, 0.78, -1.57]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_279.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_280.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.829, 0.78, -1.57]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_282.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_283.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.868, 0.78, -1.499]} rotation={[Math.PI, 0, Math.PI]} scale={[0.05, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_438.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_439.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.998, 0.78, -1.499]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_252.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_253.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.957, 0.78, -1.57]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_264.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_265.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.998, 0.78, -1.533]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_255.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_256.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.829, 0.78, -1.533]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_285.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_286.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.789, 0.78, -1.533]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_288.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_289.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.873, 0.78, -1.533]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_291.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_292.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.916, 0.78, -1.533]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_294.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_295.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-1.038, 0.78, -1.533]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_258.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_259.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.998, 0.78, -1.57]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_261.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_262.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.957, 0.78, -1.533]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_267.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_268.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.949, 0.78, -1.499]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_270.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_271.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-1.038, 0.78, -1.499]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_242.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_243.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.787, 0.78, -1.499]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_297.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_298.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.703, 0.78, -1.499]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_300.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_301.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.743, 0.78, -1.499]} rotation={[Math.PI, 0, Math.PI]} scale={[0.015, 0.002, 0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_303.geometry} material={materials['keyboard_light.052']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_304.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-0.671, 1.07, -1.91]} rotation={[-Math.PI / 2, -1.571, 0]} scale={[0.14, 0.814, 0.351]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_102.geometry} material={materials['Material.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_103.geometry} material={materials['Material.104']} />
      </group>
      <group position={[-0.671, 0.755, -1.578]} rotation={[0, -1.571, 0]} scale={[0.166, 0.389, 0.574]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_132.geometry} material={materials['Material.027']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_133.geometry} material={materials['Matériau.030']} />
      </group>
      <group position={[-1.274, 1.07, -1.661]} rotation={[0, -Math.PI / 4, Math.PI / 2]} scale={[0.14, 0.814, 0.351]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_135.geometry} material={materials['Material.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_136.geometry} material={materials['Material.104']} />
      </group>
      <group position={[-0.067, 1.07, -1.658]} rotation={[-Math.PI, -Math.PI / 4, -Math.PI / 2]} scale={[0.14, 0.814, 0.351]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_140.geometry} material={materials['Material.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_141.geometry} material={materials['Material.104']} />
      </group>
      <group position={[-0.762, 0.769, -1.578]} rotation={[0, -1.571, 0]} scale={[0.105, 0.248, 0.365]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_239.geometry} material={materials['Material.092']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_240.geometry} material={materials['Material.027']} />
      </group>
      <group position={[-0.671, 0.727, -1.699]} rotation={[0, -1.571, 0]} scale={[0.382, 1.144, 1.33]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_95.geometry} material={materials.Material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_96.geometry} material={materials['keyboard_light.052']} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Object_79.geometry} material={materials['Matériau.020']} position={[-1.475, 0.18, -1.705]} rotation={[Math.PI, 0, Math.PI]} scale={[0.234, 0.153, 0.291]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_83.geometry} material={materials['Matériau.018']} position={[0.139, 0.525, -1.705]} rotation={[Math.PI, 0, Math.PI]} scale={[0.234, 0.153, 0.291]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_81.geometry} material={materials['Matériau.019']} position={[-1.475, 0.525, -1.705]} rotation={[Math.PI, 0, Math.PI]} scale={[0.234, 0.153, 0.291]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_85.geometry} material={materials['Matériau.017']} position={[0.139, 0.18, -1.705]} rotation={[Math.PI, 0, Math.PI]} scale={[0.234, 0.153, 0.291]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_87.geometry} material={materials.lever} position={[-1.475, 0.298, -1.458]} rotation={[Math.PI, 0, Math.PI]} scale={[0.098, 0.006, 0.064]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_89.geometry} material={materials.lever} position={[-1.475, 0.638, -1.458]} rotation={[Math.PI, 0, Math.PI]} scale={[0.098, 0.006, 0.064]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_91.geometry} material={materials.lever} position={[0.139, 0.638, -1.458]} rotation={[Math.PI, 0, Math.PI]} scale={[0.098, 0.006, 0.064]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_93.geometry} material={materials.lever} position={[0.139, 0.298, -1.458]} rotation={[Math.PI, 0, Math.PI]} scale={[0.098, 0.006, 0.064]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_98.geometry} material={materials.material_0} position={[-1.475, 0.7, -1.705]} rotation={[Math.PI, 0, Math.PI]} scale={[0.205, 0.025, 0.255]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_100.geometry} material={materials.material_0} position={[0.14, 0.7, -1.705]} rotation={[Math.PI, 0, Math.PI]} scale={[0.205, 0.025, 0.255]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_130.geometry} material={materials.screen} position={[-0.674, 0.759, -1.977]} scale={[0.033, 0.004, 0.033]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_138.geometry} material={materials.screen} position={[-1.323, 0.759, -1.707]} rotation={[0, Math.PI / 4, 0]} scale={[0.033, 0.004, 0.033]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_143.geometry} material={materials.screen} position={[-0.022, 0.759, -1.707]} rotation={[0, -Math.PI / 4, 0]} scale={[0.033, 0.004, 0.033]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_149.geometry} material={materials.lever} position={[-0.657, 0.365, -1.008]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.021, 0.061, 0.061]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_171.geometry} material={materials['Matériau.007']} position={[0.433, 1.03, -1.684]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.252, 0.164, 0.313]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_173.geometry} material={materials.lever} position={[0.323, 1.344, -1.415]} rotation={[Math.PI, 0, Math.PI]} scale={[0.024, 0.004, 0.016]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_175.geometry} material={materials.lever} position={[0.403, 1.344, -1.415]} rotation={[Math.PI, 0, Math.PI]} scale={[0.016, 0.002, 0.01]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_177.geometry} material={materials.lever} position={[0.472, 1.344, -1.415]} rotation={[Math.PI, 0, Math.PI]} scale={[0.016, 0.002, 0.01]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_213.geometry} material={materials['keyboard_light.052']} position={[0.306, 0.961, -1.781]} rotation={[-2.269, 0, -Math.PI / 2]} scale={[0.094, 0.003, 0.016]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_215.geometry} material={materials['keyboard_light.052']} position={[0.306, 1.082, -1.781]} rotation={[-2.269, 0, -Math.PI / 2]} scale={[0.065, 0.002, 0.011]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_217.geometry} material={materials['keyboard_light.052']} position={[0.306, 0.893, -1.716]} rotation={[-2.269, 0, -Math.PI / 2]} scale={[0.094, 0.003, 0.016]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_219.geometry} material={materials['keyboard_light.052']} position={[0.306, 0.877, -1.599]} rotation={[-2.269, 0, -Math.PI / 2]} scale={[0.069, 0.002, 0.012]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_223.geometry} material={materials['Material.025']} position={[0.546, 1.342, -1.412]} rotation={[Math.PI, 0, Math.PI]} scale={[0.001, 0.001, 0.01]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_147.geometry} material={materials['Material.103']} position={[-0.661, 0.104, -1.011]} scale={[0.045, 0.025, 0.045]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_154.geometry} material={materials.lever} position={[-0.421, 0.052, -0.935]} rotation={[-Math.PI / 2, 0, -1.92]} scale={[0.027, 0.012, 0.027]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_156.geometry} material={materials.lever} position={[-0.512, 0.052, -1.215]} rotation={[-Math.PI / 2, 0, -0.611]} scale={[0.027, 0.012, 0.027]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_145.geometry} material={materials['Material.001']} position={[-0.66, 0.178, -1.01]} rotation={[3.135, -0.046, 0.023]} scale={[0.024, 0.012, 0.024]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_158.geometry} material={materials.lever} position={[-0.811, 0.052, -1.216]} rotation={[-Math.PI / 2, 0, 0.611]} scale={[0.027, 0.012, 0.027]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_160.geometry} material={materials.lever} position={[-0.905, 0.052, -0.932]} rotation={[-Math.PI / 2, 0, 1.92]} scale={[0.027, 0.012, 0.027]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_162.geometry} material={materials.lever} position={[-0.662, 0.052, -0.754]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[0.027, 0.012, 0.027]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_179.geometry} material={materials.material_0} position={[0.549, 1.323, -1.428]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.013, -0.004, -0.013]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_225.geometry} material={materials['Matériau.026']} position={[0.434, 1.198, -1.443]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-0.072, -0.005, -0.072]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_209.geometry} material={materials['Matériau.027']} position={[0.434, 1.031, -1.443]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-0.072, -0.005, -0.072]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_211.geometry} material={materials['Matériau.029']} position={[0.434, 0.865, -1.443]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-0.072, -0.005, -0.072]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_221.geometry} material={materials['Material.024']} position={[0.434, 1.195, -1.878]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-0.072, -0.005, -0.072]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_248.geometry} material={materials.material_0} position={[-0.266, 0.776, -1.61]} rotation={[1.343, 0.13, -2.08]} scale={[0.015, 0.002, 0.011]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_250.geometry} material={materials['Material.099']} position={[0.597, 1.03, -1.685]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[0.203, 0.203, 0.251]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_493.geometry} material={materials['keyboard_light.052']} position={[0.307, 1.178, -1.52]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.09} />
      <group position={[1.293, 0, -0.932]} rotation={[-Math.PI / 2, 0, -1.171]} scale={0.302}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[-9.114, -0.846, 84.666]} rotation={[-Math.PI / 2, 0, 0.495]} scale={100}>
            <mesh castShadow receiveShadow geometry={nodes.Guitar_Stand_Guitar_Stand_0.geometry} material={materials.Guitar_Stand} position={[1.07, 1.698, 0.049]} />
          </group>
          <group position={[-12.809, 258.612, 80.448]} rotation={[-1.875, -0.174, 0.504]} scale={100}>
            <mesh castShadow receiveShadow geometry={nodes.Guitar_Telecaster_Guitar_telecaster_0.geometry} material={materials.Guitar_telecaster} position={[1.13, 1.542, 0.613]} />
          </group>
          <group position={[-230.406, 0, -90]} rotation={[-Math.PI / 2, 0, Math.PI / 6]} scale={110}>
            <mesh castShadow receiveShadow geometry={nodes.Vox_Amp_vox_amp_0.geometry} material={materials.vox_amp} position={[1.056, 0.798, 0.045]} />
          </group>
        </group>
      </group>
      <group position={[0, 1.75, -1.96]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.924, 1, 1]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[-0.129, -2.133, -2.525]}>
            <mesh castShadow receiveShadow geometry={nodes.Shelf_Wall_1_WallMount_Material_0.geometry} material={materials.WallMount_Material} scale={[1, 2.047, 1]} />
          </group>
        </group>
      </group>
      <group position={[0.084, 0, -2.175]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.059, 1, 1]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh castShadow receiveShadow geometry={nodes.Object_6.geometry} material={materials['.001']} />
          <mesh castShadow receiveShadow geometry={nodes.Object_4001.geometry} material={materials.material} position={[0, 1, 0]} rotation={[Math.PI / 2, 0, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/bedroom.glb')
