/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 express.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function ExpressModel(props) {
  const { nodes, materials } = useGLTF('/portfolio3d/models/express.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-0.001, 0, 0]}>
        <mesh geometry={nodes.Sphere_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Sphere_2.geometry} material={materials['Material.004']} />
      </group>
    </group>
  )
}

useGLTF.preload('/portfolio3d/models/express.glb')
