/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 html.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const HtmlModel = (props) => {
  const { nodes, materials } = useGLTF('/portfolio3d/models/html.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Curve.geometry} material={materials['Material.001']} position={[-0.032, 0.047, -0.018]} rotation={[Math.PI / 2, -0.002, -Math.PI / 2]} />
      <mesh geometry={nodes.Curve001.geometry} material={materials['SVGMat.001']} position={[-0.022, 0.061, -0.018]} rotation={[Math.PI / 2, -0.002, -Math.PI / 2]} scale={1.161} />
    </group>
  )
}

useGLTF.preload('/portfolio3d/models/html.glb')

export default HtmlModel;
