/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 html.glb 
Author: edgargarciaa (https://sketchfab.com/edgargarciaa)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/html5-logo-479bbf9062de4b3196f08e52d1c12821
Title: html5 logo
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const HtmlModel = (props) => {
  const { nodes, materials } = useGLTF('/models/html.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.014, 0.001, 0]} rotation={[-Math.PI / 2, 0.006, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[11.813, 52.914, -1.08]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={82.789}>
            <mesh geometry={nodes.Plane001_orange_0.geometry} material={materials.orange} />
            <mesh geometry={nodes['Plane001_orange-lite_0'].geometry} material={materials['orange-lite']} />
          </group>
          <mesh geometry={nodes['Plane_escudo-2_0'].geometry} material={materials['escudo-2']} position={[0, 0, -1.08]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
          <mesh geometry={nodes.Plane002_five_0.geometry} material={materials.five} position={[61.853, 307.492, 35.171]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/html.glb')

export default HtmlModel;