/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 js.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const JsModel = (props) => {
  const { nodes, materials } = useGLTF('/portfolio3d/models/js.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.074, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.back.geometry} material={materials.back} />
        <mesh geometry={nodes.LOGO.geometry} material={materials.logo} position={[0.534, 0.4, 0.996]} />
      </group>
    </group>
  )
}

useGLTF.preload('/portfolio3d/models/js.glb')

export default JsModel;
