/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 loader.glb 
Author: yelaman.arts (https://sketchfab.com/elamanbolushan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/loading-animation-fe9d25c88165462582454f85fad69e81
Title: Loading animation
*/

import React, {useEffect, useRef} from 'react'
import {useGLTF, useAnimations} from '@react-three/drei'

const LoaderModel = (props) => {
    const group = useRef()
    const {nodes, materials, animations} = useGLTF('/portfolio3d/models/loader.glb')
    const {actions} = useAnimations(animations, group);
    useEffect(() => {
        actions["Take 01"]?.reset().play();
    }, []);
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group name="Sketchfab_model" position={[0, -0.292, -0.286]} rotation={[-0.021, 0, 0]}>
                    <group name="Root">
                        <group name="Text" scale={1.1}>
                            <mesh name="Text_0" geometry={nodes.Text_0.geometry} material={materials.blue}/>
                        </group>
                        <group name="Text001" position={[1.477, 0.243, 0.017]}>
                            <mesh name="Text001_0" geometry={nodes.Text001_0.geometry} material={materials.blue}/>
                        </group>
                        <group name="Text002" position={[1.477, 0.243, 0.017]}>
                            <mesh name="Text002_0" geometry={nodes.Text002_0.geometry} material={materials.blue}/>
                        </group>
                        <group name="Text003" position={[1.477, 0.243, 0.017]}>
                            <mesh name="Text003_0" geometry={nodes.Text003_0.geometry} material={materials.blue}/>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/portfolio3d/models/loader.glb')

export default LoaderModel;