/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 nodejs.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function NodejsModel(props) {
  const { nodes, materials } = useGLTF('/portfolio3d/models/nodejs.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere_1.geometry} material={materials.Material} />
      <mesh geometry={nodes.Sphere_2.geometry} material={materials['Material.002']} />
    </group>
  )
}

useGLTF.preload('/portfolio3d/models/nodejs.glb')
