/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 stars.glb 
Author: AjaxGb (https://sketchfab.com/ajaxgb)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/extracted-minecraft-java-editions-stars-c8868b7ffc4a473eb5cd9203a59e3650
Title: [Extracted] Minecraft Java Edition's Stars
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function StarsModel(props) {
    const {scale} = props;
  const { nodes, materials } = useGLTF('/portfolio3d/models/stars.glb')
  return (
    <group scale={[scale, scale, scale]} {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.star} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/portfolio3d/models/stars.glb')
